version: "2"
services:
  postgresql:
    image: "docker.io/bitnami/postgresql:11-debian-10"
    container_name: postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
  
  keycloak:
    image: docker.io/bitnami/keycloak:11-debian-10
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
  
  grafana:
    build: grafana
    container_name: grafana
    ports:
      - "3000:3000"
  

volumes:
  postgresql_data:
    driver: local
